spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/css_database
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=admin
spring.security.user.password=admin
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=5174
jwt.secret=bWVkZGxMb2lkZWE5MzA4dTJpaGZld2pkc3Bpa2hiaWlqZGZkc2ZzZmVmZXczMzJyM2V3
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# logging.level.org.springframework.security=DEBUG


# PostgreSQL Passwort Privat: password