export type GameState = {
  money: number;
  inventory: number;
  gpuPerSecond: number;
  demand: number;
  marketingLevel: number;
  factoryLevel: number;
  pricePerGpu: number;
  lastSavedAt: number;
  purchasedUpgradeIds: string[];

  lifetimeMoney: number;
  prestigePoints: number;
  totalPrestigePoints: number;
  prestigeCount: number;
};

export type OneTimeUpgrade = {
  id: string;
  name: string;
  description: string;
  cost: number;

  productionMultiplier?: number;
  demandMultiplier?: number;
};

export const ONE_TIME_UPGRADES: OneTimeUpgrade[] = [
  {
    id: "cheap-thermal-paste",
    name: "Günstige Wärmeleitpaste",
    description: "Etwas bessere Kühlung erlaubt höhere Taktraten. Produktion +5%.",
    cost: 15000,
    productionMultiplier: 1.05,
  },
  {
    id: "faster-soldering-iron",
    name: "Schnellere Lötkolben",
    description: "Die manuelle Montage in der Werkstatt geht flotter von der Hand. Produktion +10%.",
    cost: 45000,
    productionMultiplier: 1.1,
  },
  {
    id: "local-newspaper-ads",
    name: "Anzeige im Lokalblatt",
    description: "Die Nachbarschaft wird auf deine Rechenmonster aufmerksam. Nachfrage +10%.",
    cost: 75000,
    demandMultiplier: 1.1,
  },
  {
    id: "better-tools",
    name: "Bessere Maschinen",
    description: "Höherwertiges Werkzeug für die Fertigung. Produktion +25%.",
    cost: 125000,
    productionMultiplier: 1.25,
  },
  {
    id: "warehouse-stacking",
    name: "Optimierte Lagerregale",
    description: "Bessere Logistik auf engem Raum spart wertvolle Zeit. Produktion +10%.",
    cost: 220000,
    productionMultiplier: 1.1,
  },
  {
    id: "social-media-ads",
    name: "Social-Media-Werbung",
    description: "Gezielte Kampagnen auf den größten Plattformen. Nachfrage +30%.",
    cost: 400000,
    demandMultiplier: 1.3,
  },
  {
    id: "rgb-everything",
    name: "RGB-Beleuchtung",
    description: "Kunden lieben bunte Lichter an ihrer Hardware. Nachfrage +20%.",
    cost: 650000,
    demandMultiplier: 1.2,
  },
  {
    id: "quality-branding",
    name: "Qualitätsmanagement I",
    description: "Ein offizielles Siegel für Zuverlässigkeit. Produktion & Nachfrage +15%.",
    cost: 1000000,
    productionMultiplier: 1.15,
    demandMultiplier: 1.15,
  },
  {
    id: "better-tools2",
    name: "Bessere Maschinen II",
    description: "Präzisionswerkzeuge für komplexere Chip-Architekturen. Produktion +25%.",
    cost: 1250000,
    productionMultiplier: 1.25,
  },
  {
    id: "social-media-ads2",
    name: "Social-Media-Werbung II",
    description: "Virale Marketing-Aktionen erhöhen die Sichtbarkeit massiv. Nachfrage +30%.",
    cost: 1500000,
    demandMultiplier: 1.3,
  },
  {
    id: "quality-branding2",
    name: "Qualitätsmanagement II",
    description: "Deine Marke steht nun weltweit für Hochleistung. Produktion & Nachfrage +15%.",
    cost: 1750000,
    productionMultiplier: 1.15,
    demandMultiplier: 1.15,
  },
  {
    id: "tech-blog-review",
    name: "Tech-Blog Review",
    description: "Ein bekannter Hardware-Guru vergibt eine Bestnote. Nachfrage +25%.",
    cost: 2800000,
    demandMultiplier: 1.25,
  },
  {
    id: "buy_competitors1",
    name: "Konkurrenten aufkaufen",
    description: "Übernahme kleinerer Fabriken und deren Patente. Produktion & Nachfrage +35%.",
    cost: 4000000,
    productionMultiplier: 1.35,
    demandMultiplier: 1.35,
  },
  {
    id: "ai_use1",
    name: "Einsatz von KI",
    description: "KI-Algorithmen optimieren das Chip-Layout in Echtzeit. Produktion & Nachfrage +15%.",
    cost: 5000000,
    productionMultiplier: 1.15,
    demandMultiplier: 1.15,
  },
  {
    id: "bulk-fan-contracts",
    name: "Großabnehmer-Lüfterdeal",
    description: "Günstigere Bauteile beschleunigen den Montageprozess. Produktion +20%.",
    cost: 7000000,
    productionMultiplier: 1.2,
  },
  {
    id: "automated_assembly_lines1",
    name: "Automatisierte Fertigungsstraßen",
    description: "Roboter übernehmen die Fließbandarbeit. Produktion +45%.",
    cost: 8500000,
    productionMultiplier: 1.45,
  },
  {
    id: "global_influencer_campaign1",
    name: "Globale Influencer-Kampagne",
    description: "Die größten Streamer der Welt zeigen deine Hardware. Nachfrage +50%.",
    cost: 12000000,
    demandMultiplier: 1.5,
  },
  {
    id: "refurbished-program",
    name: "Zertifiziertes Refurbished-Programm",
    description: "Wiederaufbereitete Karten erschließen neue Käuferschichten. Nachfrage +20%.",
    cost: 15000000,
    demandMultiplier: 1.2,
  },
  {
    id: "premium_cooling_design1",
    name: "Premium-Kühldesign",
    description: "Kühlkörper aus reinem Kupfer für maximale Leistung. Produktion & Nachfrage +25%.",
    cost: 18000000,
    productionMultiplier: 1.25,
    demandMultiplier: 1.25,
  },
  {
    id: "liquid-cooling-lab",
    name: "Wasserkühlung-Speziallabor",
    description: "Enthusiasten-Karten für den Mainstream-Markt. Produktion +30%.",
    cost: 22000000,
    productionMultiplier: 1.3,
  },
  {
    id: "chip_supplier_contract1",
    name: "Exklusiver Chip-Liefervertrag",
    description: "Sichere dir den Vorrang bei der neuesten Halbleiter-Generation. Produktion +60%.",
    cost: 26000000,
    productionMultiplier: 1.6,
  },
  {
    id: "esports_sponsoring1",
    name: "E-Sport-Sponsoring",
    description: "Dein Logo auf den Trikots der Weltmeister. Nachfrage +65%.",
    cost: 35000000,
    demandMultiplier: 1.65,
  },
  {
    id: "custom-firmware-suite",
    name: "Eigene Firmware-Suite",
    description: "Optimierte Software für maximale Hardware-Effizienz. Produktion +25%.",
    cost: 42000000,
    productionMultiplier: 1.25,
  },
  {
    id: "factory_robotics1",
    name: "Roboter-Montage",
    description: "Vollautomatische Bestückung der Platinen rund um die Uhr. Produktion +75%.",
    cost: 50000000,
    productionMultiplier: 1.75,
  },
  {
    id: "automated-testing-rigs",
    name: "Automatisierte Teststände",
    description: "Kürzere Qualitätskontrollen bei höherer Präzision. Produktion +30%.",
    cost: 65000000,
    productionMultiplier: 1.3,
  },
  {
    id: "luxury_gpu_series1",
    name: "Luxus-GPU-Serie",
    description: "Limitierte Editionen für Sammler und Profis. Produktion & Nachfrage +40%.",
    cost: 75000000,
    productionMultiplier: 1.4,
    demandMultiplier: 1.4,
  },
  {
    id: "global_distribution_network1",
    name: "Globales Vertriebsnetz",
    description: "Deine GPUs sind nun in jedem Land der Erde sofort verfügbar. Nachfrage +85%.",
    cost: 110000000,
    demandMultiplier: 1.85,
  },
  {
    id: "retail-exclusivity-deals",
    name: "Exklusivverträge mit Einzelhandel",
    description: "Deine Karten erhalten die prominentesten Regalplätze. Nachfrage +40%.",
    cost: 140000000,
    demandMultiplier: 1.4,
  },
  {
    id: "nano_fabrication1",
    name: "Nano-Fertigung",
    description: "Fertigung im 1-Nanometer-Bereich für extreme Chipdichte. Produktion +100%.",
    cost: 160000000,
    productionMultiplier: 2,
  },
  {
    id: "hype_launch_events1",
    name: "Weltweite Launch-Events",
    description: "Tausende Fans stehen für deine neuen Modelle Schlange. Nachfrage +100%.",
    cost: 230000000,
    demandMultiplier: 2,
  },
  {
    id: "ai_optimized_supply_chain1",
    name: "KI-optimierte Lieferkette",
    description: "Keine Verzögerungen mehr durch intelligente Logistik. Produktion & Nachfrage +60%.",
    cost: 350000000,
    productionMultiplier: 1.6,
    demandMultiplier: 1.6,
  },
  {
    id: "green-energy-manufacturing",
    name: "Ökostrom-Großproduktion",
    description: "Staatliche Subventionen für klimaneutrale Fabriken. Produktion +35%.",
    cost: 450000000,
    productionMultiplier: 1.35,
  },
  {
    id: "quantum_quality_control1",
    name: "Quanten-Qualitätskontrolle",
    description: "Fehlererkennung auf subatomarer Ebene. Produktion +125%.",
    cost: 520000000,
    productionMultiplier: 2.25,
  },
  {
    id: "global-logistics-fleet",
    name: "Eigene Logistik-Flotte",
    description: "Unabhängigkeit von Reedereien durch eigene Frachtschiffe. Nachfrage +50%.",
    cost: 700000000,
    demandMultiplier: 1.5,
  },
  {
    id: "cult_brand_status1",
    name: "Kultmarken-Status",
    description: "Kunden kaufen deine Produkte blind vor jedem Release. Nachfrage +140%.",
    cost: 800000000,
    demandMultiplier: 2.4,
  },
  {
    id: "mega_factory1",
    name: "Mega-Fabrik",
    description: "Ein ganzer Industriekomplex nur für die Grafikkarten-Produktion. Produktion +175%.",
    cost: 1200000000,
    productionMultiplier: 2.75,
  },
  {
    id: "exclusive_oem_deals1",
    name: "Exklusive OEM-Deals",
    description: "Jeder neue PC wird standardmäßig mit deiner GPU ausgeliefert. Produktion & Nachfrage +100%.",
    cost: 1800000000,
    productionMultiplier: 2,
    demandMultiplier: 2,
  },
  {
    id: "autonomous_factories1",
    name: "Autonome Fabriken",
    description: "Vollständige Produktion ohne menschlichen Eingriff. Produktion +250%.",
    cost: 2800000000,
    productionMultiplier: 3.5,
  },
  {
    id: "worldwide_waiting_lists1",
    name: "Weltweite Wartelisten",
    description: "Die Vorbestellungen übersteigen die Produktion um Jahre. Nachfrage +250%.",
    cost: 4200000000,
    demandMultiplier: 3.5,
  },
  {
    id: "silicon_empire1",
    name: "Silizium-Imperium",
    description: "Beherrschung des gesamten Marktes vom Rohstoff bis zum Endprodukt. Produktion & Nachfrage +200%.",
    cost: 6500000000,
    productionMultiplier: 3,
    demandMultiplier: 3,
  },
  {
    id: "hypnosis",
    name: "Massenhypnose",
    description: "Menschen geben ihr gesamtes Geld für GPUs aus. Nachfrage +300%.",
    cost: 6500000000,
    demandMultiplier: 4,
  },
  {
    id: "orbital_datacenter_contracts1",
    name: "Orbitale Rechenzentrumsverträge",
    description: "Deine Chips berechnen die Satellitendaten der Zukunft. Nachfrage +400%.",
    cost: 10000000000,
    demandMultiplier: 5,
  },
  {
    id: "self_replicating_factories1",
    name: "Selbstreplizierende Fabriken",
    description: "Fabriken, die sich selbst erweitern und neue Fabriken bauen. Produktion +500%.",
    cost: 16000000000,
    productionMultiplier: 6,
  },
  {
    id: "planetary_gpu_monopoly1",
    name: "Planetarisches GPU-Monopol",
    description: "Es gibt keine Alternativen mehr zu deiner Hardware. Produktion & Nachfrage +400%.",
    cost: 25000000000,
    productionMultiplier: 5,
    demandMultiplier: 5,
  },
  {
    id: "multidimensional_ads1",
    name: "Multidimensionale Werbespots",
    description: "Deine Werbung erscheint direkt in den Träumen der Kunden. Nachfrage +15000%.",
    cost: 35000000000000,
    demandMultiplier: 151,
  },
  {
    id: "dyson_cloud_compute1",
    name: "Dyson-Cloud-Compute",
    description: "Nutze die Energie ganzer Sonnen für deine Server-Cluster. Nachfrage +750%.",
    cost: 40000000000,
    demandMultiplier: 8.5,
  },
  {
    id: "tachyon_production1",
    name: "Tachyonen-Fertigung",
    description: "GPUs werden fertiggestellt, bevor der Auftrag überhaupt eingeht. Produktion +18000%.",
    cost: 60000000000000,
    productionMultiplier: 181,
  },
  {
    id: "quantum_gpu_foundry1",
    name: "Quanten-GPU-Foundry",
    description: "Fertigung in parallelen Zuständen für maximale Effizienz. Produktion +900%.",
    cost: 65000000000,
    productionMultiplier: 10,
  },
  {
    id: "interstellar_gpu_brand1",
    name: "Interstellare GPU-Marke",
    description: "Verkaufe deine Hardware an Zivilisationen in fernen Galaxien. Produktion & Nachfrage +800%.",
    cost: 100000000000,
    productionMultiplier: 9,
    demandMultiplier: 9,
  },
  {
    id: "gpu_consciousness1",
    name: "GPU-Selbstbewusstsein",
    description: "Die Hardware optimiert ihren eigenen Code während des Betriebs. Produktion & Nachfrage +14000%.",
    cost: 100000000000000,
    productionMultiplier: 141,
    demandMultiplier: 141,
  },
  {
    id: "corruption_network1",
    name: "Korruptionsnetzwerk aufbauen",
    description: "Niemand kann dich mehr aufhalten, Gesetze gelten nicht für dich. Produktion & Nachfrage +1600%.",
    cost: 150000000000,
    productionMultiplier: 18,
    demandMultiplier: 18,
  },
  {
    id: "dark_matter_foundry1",
    name: "Dunkle-Materie-Schmiede",
    description: "Nutze die unsichtbare Masse des Universums als Rohstoff. Produktion +25000%.",
    cost: 180000000000000,
    productionMultiplier: 251,
  },
  {
    id: "global_lobby_network1",
    name: "Globales Lobby-Netzwerk",
    description: "Politik wird nur noch im Sinne deines Unternehmens gemacht. Produktion & Nachfrage +2000%.",
    cost: 250000000000,
    productionMultiplier: 21,
    demandMultiplier: 21,
  },
  {
    id: "time_loop_efficiency1",
    name: "Zeitschleifen-Logistik",
    description: "Ein Arbeitstag wird so oft wiederholt, bis er perfekt ist. Produktion +30000%.",
    cost: 320000000000000,
    productionMultiplier: 301,
  },
  {
    id: "gpu_stock_market_hype1",
    name: "GPU-Börsenhype auslösen",
    description: "Deine Aktienkurse sprengen jede bekannte Skala. Nachfrage +3000%.",
    cost: 400000000000,
    demandMultiplier: 31,
  },
  {
    id: "galactic_billboards1",
    name: "Sternenbild-Marketing",
    description: "Sterne werden zu deinem Logo neu angeordnet. Nachfrage +35000%.",
    cost: 550000000000000,
    demandMultiplier: 351,
  },
  {
    id: "fully_dark_factory1",
    name: "Lichtlose 24/7-Fabriken",
    description: "Maschinen brauchen kein Licht, nur Silizium und Strom. Produktion +3500%.",
    cost: 650000000000,
    productionMultiplier: 36,
  },
  {
    id: "molecular_reassembly1",
    name: "Molekulare GPU-Reassemblierung",
    description: "Verwandle gewöhnliche Materie direkt in fertige Hochleistungschips. Produktion +45000%.",
    cost: 900000000000000,
    productionMultiplier: 451,
  },
  {
    id: "ai_ceo_takeover1",
    name: "KI als CEO einsetzen",
    description: "Maximale Gewinnoptimierung ohne menschliche Emotionen. Produktion & Nachfrage +2800%.",
    cost: 1000000000000,
    productionMultiplier: 29,
    demandMultiplier: 29,
  },
  {
    id: "reality_warping_r_d1",
    name: "Realitätskrümmende Forschung",
    description: "Die Gesetze der Physik sind nun auf dein Unternehmen angepasst. Produktion & Nachfrage +30000%.",
    cost: 1500000000000000,
    productionMultiplier: 301,
    demandMultiplier: 301,
  },
  {
    id: "moon_silicon_mines1",
    name: "Siliziumminen auf dem Mond",
    description: "Extraktion reinster Rohstoffe direkt vom Erdtrabanten. Produktion +5000%.",
    cost: 1750000000000,
    productionMultiplier: 51,
  },
  {
    id: "neuro_link_preorders1",
    name: "Neuro-Link Direktbestellung",
    description: "Der Kaufimpuls wird direkt im Gehirn des Kunden ausgelöst. Nachfrage +60000%.",
    cost: 2800000000000000,
    demandMultiplier: 601,
  },
  {
    id: "mandatory_gpu_subscription1",
    name: "GPU-Abo für alle Geräte",
    description: "Jedes elektronische Gerät weltweit benötigt eine aktive Lizenz von dir. Nachfrage +6000%.",
    cost: 2750000000000,
    demandMultiplier: 61,
  },
  {
    id: "anti_entropy_factories1",
    name: "Anti-Entropie-Fabriken",
    description: "Deine Maschinen werden durch Benutzung immer neuer und effizienter. Produktion +80000%.",
    cost: 5000000000000000,
    productionMultiplier: 801,
  },
  {
    id: "parallel_universe_supply_chain1",
    name: "Lieferkette aus Paralleluniversen",
    description: "Zapfe die unendlichen Ressourcen anderer Realitäten an. Produktion & Nachfrage +4500%.",
    cost: 4500000000000,
    productionMultiplier: 46,
    demandMultiplier: 46,
  },
  {
    id: "black_hole_cooling1",
    name: "Schwarzes-Loch-Kühlung",
    description: "Singularitäten absorbieren jegliche Abwärme deiner Fabriken. Produktion +8000%.",
    cost: 7500000000000,
    productionMultiplier: 81,
  },
  {
    id: "void_energy_tapping1",
    name: "Leerenenergie-Anzapfung",
    description: "Unerschöpfliche Energie aus dem Nichts zwischen den Dimensionen. Produktion +100000%.",
    cost: 9000000000000000,
    productionMultiplier: 1001,
  },
  {
    id: "galactic_gamer_cult1",
    name: "Galaktischer Gamer-Kult",
    description: "GPUs sind das Zentrum einer neuen universalen Religion geworden. Nachfrage +9000%.",
    cost: 12000000000000,
    demandMultiplier: 91,
  },
  {
    id: "ancestral_gpu_memory1",
    name: "Genetisches GPU-Gedächtnis",
    description: "Das Bedürfnis nach deiner Hardware ist nun fest in der DNA verankert. Nachfrage +120000%.",
    cost: 16000000000000000,
    demandMultiplier: 1201,
  },
  {
    id: "universal_gpu_singularity1",
    name: "Universelle GPU-Singularität",
    description: "Das gesamte Universum verschmilzt zu einer einzigen Recheneinheit. Produktion & Nachfrage +12000%.",
    cost: 20000000000000,
    productionMultiplier: 121,
    demandMultiplier: 121,
  },
  {
    id: "quantum_teleportation_shipping1",
    name: "Quanten-Sofort-Versand",
    description: "GPUs befinden sich am Zielort, noch bevor sie losgeschickt wurden. Nachfrage +150000%.",
    cost: 30000000000000000,
    demandMultiplier: 1501,
  },
  {
    id: "string_theory_optimization1",
    name: "Stringtheorie-Optimierung",
    description: "Die Schwingungen des Universums werden zur Platinenherstellung genutzt. Produktion +200000%.",
    cost: 55000000000000000,
    productionMultiplier: 2001,
  },
  {
    id: "subconscious_branding1",
    name: "Subliminales Universalkonzept",
    description: "Deine Marke ist nun ein fester Bestandteil der menschlichen Sprache. Produktion & Nachfrage +150000%.",
    cost: 100000000000000000,
    productionMultiplier: 1501,
    demandMultiplier: 1501,
  },
  {
    id: "event_horizon_mining1",
    name: "Ereignishorizont-Bergbau",
    description: "Sammle exotische Materie direkt am Rand schwarzer Löcher. Produktion +350000%.",
    cost: 200000000000000000,
    productionMultiplier: 3501,
  },
  {
    id: "multi_timeline_merger1",
    name: "Zeitlinien-Fusion",
    description: "Importiere die Produktionskapazitäten aus tausenden Zeitlinien gleichzeitig. Produktion +500000%.",
    cost: 400000000000000000,
    productionMultiplier: 5001,
  },
  {
    id: "concept_of_gpu_ascension1",
    name: "Metaphysische GPU-Erhöhung",
    description: "Deine Hardware ist nicht mehr physisch, sondern ein reiner Gedankenzustand. Nachfrage +750000%.",
    cost: 800000000000000000,
    demandMultiplier: 7501,
  },
  {
    id: "zero_point_factories1",
    name: "Nullpunkt-Fabriken",
    description: "Herstellung direkt aus der Nullpunktsenergie des Vakuums. Produktion +1000000%.",
    cost: 1500000000000000000,
    productionMultiplier: 10001,
  },
  {
    id: "universal_currency_replacement1",
    name: "GPU-Standard-Währung",
    description: "Alle anderen Währungen wurden abgeschafft, es zählt nur noch Rechenpower. Nachfrage +1500000%.",
    cost: 3000000000000000000,
    demandMultiplier: 15001,
  },
  {
    id: "gravity_wave_manufacturing1",
    name: "Gravitationswellen-Formung",
    description: "Krümmung des Raumes, um perfekte Gehäuseformen zu pressen. Produktion +2500000%.",
    cost: 6000000000000000000,
    productionMultiplier: 25001,
  },
  {
    id: "thought_form_manifestation1",
    name: "Gedankenform-Manifestation",
    description: "Wer eine GPU will, lässt sie durch reine Willenskraft erscheinen. Produktion & Nachfrage +2000000%.",
    cost: 12000000000000000000,
    productionMultiplier: 20001,
    demandMultiplier: 20001,
  },
  {
    id: "holographic_universe_exploit1",
    name: "Holographischer Universums-Exploit",
    description: "Nutze Programmierfehler in der Realität für unendliche Materialkopien. Produktion +5000000%.",
    cost: 25000000000000000000,
    productionMultiplier: 50001,
  },
  {
    id: "post_scarcity_branding1",
    name: "Post-Knappheits-Marketing",
    description: "Jedes Atom im Universum existiert nur, um eine GPU zu werden. Nachfrage +8000000%.",
    cost: 50000000000000000000,
    demandMultiplier: 80001,
  },
  {
    id: "dark_energy_superhighway1",
    name: "Dunkle-Energie-Autobahn",
    description: "Warenversand über die Expansion des Universums selbst. Produktion +12000000%.",
    cost: 100000000000000000000,
    productionMultiplier: 120001,
  },
  {
    id: "simulation_theory_access1",
    name: "Admin-Zugriff auf die Simulation",
    description: "Manuelle Bearbeitung der Bestandszahlen in den Grundfesten der Welt. Produktion +20000000%.",
    cost: 250000000000000000000,
    productionMultiplier: 200001,
  },
  {
    id: "divine_gpu_mandate1",
    name: "Göttliches GPU-Mandat",
    description: "Der Besitz einer Grafikkarte ist nun die höchste moralische Pflicht. Nachfrage +35000000%.",
    cost: 600000000000000000000,
    demandMultiplier: 350001,
  },
  {
    id: "multiversal_empire1",
    name: "Multiversales Imperium",
    description: "Beherrsche alle Märkte in sämtlichen möglichen Parallelwelten. Produktion & Nachfrage +50000000%.",
    cost: 1500000000000000000000,
    productionMultiplier: 500001,
    demandMultiplier: 500001,
  },
  {
    id: "probability_manipulation1",
    name: "Wahrscheinlichkeits-Manipulation",
    description: "Die Chance, keine GPU zu kaufen, wurde mathematisch eliminiert. Nachfrage +100000000%.",
    cost: 4000000000000000000000,
    demandMultiplier: 1000001,
  },
  {
    id: "cosmic_background_noise_ads1",
    name: "Kosmische Hintergrundstrahlung-Werbung",
    description: "Das Echo des Urknalls flüstert nun deinen Markennamen. Nachfrage +250000000%.",
    cost: 10000000000000000000000,
    demandMultiplier: 2500001,
  },
  {
    id: "matter_transmutation_v21",
    name: "Totale Materie-Transmutation",
    description: "Alle chemischen Elemente des Universums wurden in Silizium umgewandelt. Produktion +500000000%.",
    cost: 30000000000000000000000,
    productionMultiplier: 5000001,
  },
  {
    id: "transdimensional_warehousing1",
    name: "Transdimensionale Lagerhaltung",
    description: "Lagerhäuser, die innen unendlich viel Platz für unendlich viele Käufer bieten. Nachfrage +750000000%.",
    cost: 85000000000000000000000,
    demandMultiplier: 7500001,
  },
  {
    id: "omega_point_production1",
    name: "Omega-Punkt-Produktion",
    description: "Das Ziel der Evolution ist die reine, vollkommene GPU-Leistung. Produktion +1500000000%.",
    cost: 250000000000000000000000,
    productionMultiplier: 15000001,
  },
  {
    id: "existential_hype_cycle1",
    name: "Existentieller Hype-Zyklus",
    description: "Eine Existenz ohne deine Hardware ist nun logisch unmöglich. Produktion & Nachfrage +1000000000%.",
    cost: 750000000000000000000000,
    productionMultiplier: 10000001,
    demandMultiplier: 10000001,
  },
  {
    id: "rewriting_the_big_bang1",
    name: "Den Urknall umschreiben",
    description: "Das Universum begann mit einer GPU, nicht mit Licht. Produktion +5000000000%.",
    cost: 2500000000000000000000000,
    productionMultiplier: 50000001,
  },
  {
    id: "galactic_rebranding_campaign1",
    name: "Galaktische Neukonstruktion",
    description: "Sämtliche Sonnensysteme wurden optisch an dein Firmendesign angepasst. Nachfrage +10000000000%.",
    cost: 10000000000000000000000000,
    demandMultiplier: 100000001,
  },
  {
    id: "beyond_the_fourth_wall1",
    name: "Durchbruch der vierten Wand",
    description: "Der Einfluss deiner Marke erreicht nun sogar die Realität des Spielers. Produktion +25000000000%.",
    cost: 50000000000000000000000000,
    productionMultiplier: 250000001,
  },
  {
    id: "infinite_recursion_loop1",
    name: "Unendliche Rekursionsschleife",
    description: "Jede gebaute GPU baut im selben Moment zwei weitere GPUs. Produktion +100000000000%.",
    cost: 250000000000000000000000000,
    productionMultiplier: 1000000001,
  },
  {
    id: "the_final_marketing_push1",
    name: "Der finale Marketing-Push",
    description: "Es gibt keine Fragen mehr. Es gibt nur noch die GPU. Nachfrage +500000000000%.",
    cost: 1000000000000000000000000000,
    demandMultiplier: 5000000001,
  },
  {
    id: "alpha_and_omega_gpu1",
    name: "Die Alpha & Omega GPU",
    description: "Der Kreis schließt sich. Alles, was war, ist und sein wird, ist GPU. Produktion & Nachfrage +1000000000000%.",
    cost: 9999999999999999999999999999,
    productionMultiplier: 10000000001,
    demandMultiplier: 10000000001,
  }
];